<script setup></script>

<template class="relative font-body">
  <div
    class="bg-light rounded-t-lg mt-14 md:mt-20 p-5 main-container lg:px-10 relative lg:w-1/2 mx-auto pb-16"
  >
    <h1 class="text-heading text-primary text-3xl text-center my-2 md:text-4xl">
      Travel Tracker Web App
    </h1>

    <p class="text-body text-dark text-lg lg:text-xl">
      I developed this app to help users track their travels and holiday
      destinations. The app was built with a mobile-first design approach,
      meaning it looks great on smaller screens and is optimized for use on
      smartphones. This allows users to easily access their travel plans
      anytime, anywhere. Here's how it works:
    </p>

    <h2 class="text-accent text-2xl md:text-3xl text-bold mb-2 mt-3">
      Home Page
    </h2>
    <p class="text-body text-dark text-lg lg:text-xl">
      On the home page, you can find details about your current holiday or the
      next upcoming trip, if there is one. If no trips are scheduled, you can go
      to the "Add Trip" tab to create a new journey.
    </p>

    <h2 class="text-accent text-2xl md:text-3xl text-bold mb-2 mt-3">
      List Page
    </h2>
    <p class="text-body text-dark text-lg lg:text-xl">
      On the list page, you can view all of your saved trips. Additionally, two
      default destinations generated by AI are provided for you to explore. I
      recommend clicking on the "View Details" button to see an example of what
      a travel plan looks like.
    </p>
    <p class="text-body text-dark text-lg lg:text-xl">
      If needed, you can delete any or all trips from the list. All additions
      and cancellations are dynamically recorded in the browser, ensuring the
      app remains personalized for each user.
    </p>

    <h2 class="text-accent text-2xl md:text-3xl text-bold mb-2 mt-3">
      Add Trip Page
    </h2>
    <p class="text-body text-dark text-lg lg:text-xl">
      On the "Add Trip" page, you can enter a new journey. It is mandatory to
      provide a title and start date for the trip. You also have the option to
      choose between a multi-day journey or a one-day break. If it's a one-day
      trip, there is no need to select an end date. Additionally, you can
      include a description of the trip. Also a photo can be uploaded to a trip
      but it is not required, otherwise a default pic will appear on the site.
    </p>
    <p class="text-body text-dark text-lg lg:text-xl mt-2">
      For multi-day trips, the app automatically generates day-by-day tabs,
      allowing you to add stops for each day. You can manage this by clicking
      the "Trip Details" button on the trip card in the "All Trips" page.
    </p>

    <h2 class="text-accent text-2xl md:text-3xl text-bold mb-2 mt-3">
      Trip Details Page
    </h2>
    <p class="text-body text-dark text-lg lg:text-xl">
      On the trip details page, you can add separate information for hotels and
      restaurants for each day of your trip. If the journey is broken down by
      days (e.g., Day 1, Day 2), each day will display its stops along with the
      corresponding hotels and restaurants. You can view the stops and
      accommodations for each day on the map by clicking the "Map" button.
    </p>
  </div>
</template>

<style scoped></style>
